package serendustry.machine.structure;

public class StructureStellarIncubator {

    public static final String[][] STELLAR_INCUBATOR = { {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                DDDDDDDDD                "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "            DDDDDDDDDDDDDDDDD            "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                  EEFEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                EEEEEEEEE                ",
            "          DDDDDDDDDDDDDDDDDDDDD          "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "             EEEEEEEEEEEEEEE             ",
            "         DDDDDDDDDDDDDDDDDDDDDDD         "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                EEEEEEEEE                ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "           EEEEE  EEEEE  EEEEE           ",
            "       DDDDDDDDDDDDDDDDDDDDDDDDDDD       "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "             EEE         EEE             ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "         EEEE               EEEE         ",
            "      DDDDDDDDDDDDDDDDDDDDDDDDDDDDD      "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "           EE               EE           ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "        EEE                   EEE        ",
            "     DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD     "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "          E                   E          ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "       EEE                     EEE       ",
            "    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD    "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "         E                     E         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "      EEE                       EEE      ",
            "    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD    "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "        E                       E        ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     EEE         EEEEEEE         EEE     ",
            "   DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD   "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "       E                         E       ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     EE        EEEEEEEEEEE        EE     ",
            "  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "      E                           E      ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    EE       EEEEEEEEEEEEEEE       EE    ",
            "  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "      E                           E      ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    EE      EEEEEEEEEEEEEEEEE      EE    ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     E                             E     ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "   EE      EEEEEEEEEEEEEEEEEEE      EE   ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     E                             E     ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "   EE      EEEEEEEEEEEEEEEEEEE      EE   ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     E                             E     ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "               EE       EE               ",
            "   EE     EEEEEEEEEEEEEEEEEEEEE     EE   ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    E                               E    ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "               EE       EE               ",
            "  EE      EEEEEEEEEEEEEEEEEEEEE      EE  ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    E                               E    ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "               EE       EE               ",
            "             EEEE       EEEE             ",
            "  EE     EEEEEEEEEEEEEEEEEEEEEEE     EE  ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    E                               E    ",
            "    E                               E    ",
            "   EE                               EE   ",
            "   EE                               EE   ",
            "  EEE          EE       EE          EEE  ",
            "  EEE          EE       EE          EEE  ",
            " EEEE        EEEE       EEEE        EEEE ",
            " EEEE    EEEEEEEEEEEEEEEEEEEEEEE    EEEE ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                   E E                   ",
            "                   E E                   ",
            "                   E E                   ",
            "                  EE EE                  ",
            "                  EE EE                  ",
            "                  EE EE                  ",
            "                 EAE EAE                 ",
            "                 EAE EAE                 ",
            "                 EAE EAE                 ",
            "                EEAE EAEE                ",
            "                EEAE EAEE                ",
            "                EEAE EAEE                ",
            "               EEAAE EAAEE               ",
            "               EEAEE EEAEE               ",
            "               EEAEE EEAEE               ",
            "              EEEAEE EEAEEE              ",
            "              EEEAEE EEAEEE              ",
            "              EEEAEE EEAEEE              ",
            "             EEEAAEE EEAAEEE             ",
            "             EEEAEEE EEEAEEE             ",
            "             EEEAEEE EEEAEEE             ",
            "            EEEEAEEE EEEAEEEE            ",
            "            EEEEAEEE EEEAEEEE            ",
            "    E       EEEEAEEE EEEAEEEE       E    ",
            "    E      EEEEEAEEE EEEAEEEEE      E    ",
            "   EE      EEEEEAEEE EEEAEEEEE      EE   ",
            "   EE      EEEAAAEEE EEEAAAEEE      EE   ",
            "  EEE     EEEEAEEEEE EEEEEAEEEE     EEE  ",
            "  EEE     EEAAAEEEEE EEEEEAAAEE     EEE  ",
            " EEEE     EEAEEEEEEE EEEEEEEAEE     EEEE ",
            " EEEE    EEEEEEEEEEEEEEEEEEEEEEE    EEEE ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                   E E                   ",
            "                   E E                   ",
            "                   E E                   ",
            "                  EE EE                  ",
            "                  EE EE                  ",
            "                  EE EE                  ",
            "                 ECE ECE                 ",
            "                 ECE ECE                 ",
            "                 ECE ECE                 ",
            "                EECE ECEE                ",
            "                EECE ECEE                ",
            "                EECE ECEE                ",
            "               EECCE ECCEE               ",
            "               EECEE EECEE               ",
            "               EECEE EECEE               ",
            "              EEECEE EECEEE              ",
            "              EEECEE EECEEE              ",
            "              EEECEE EECEEE              ",
            "             EEECCEE EECCEEE             ",
            "             EEECEEE EEECEEE             ",
            "             EEECEEE EEECEEE             ",
            "            EEEECEEE EEECEEEE            ",
            "            EEEECEEE EEECEEEE            ",
            "    E       EEEECEEE EEECEEEE       E    ",
            "    E      EEEEECEEE EEECEEEEE      E    ",
            "   EE      EEEEECEEE EEECEEEEE      EE   ",
            "   EE      EEECCCEEE EEECCCEEE      EE   ",
            "  EEE     EEEECEEEEE EEEEECEEEE     EEE  ",
            "  EEE     EECCCEEEEE EEEEECCCEE     EEE  ",
            " EEEE     EECEEEEEEE EEEEEEECEE     EEEE ",
            " EEEE    EEEEEEEEEEEEEEEEEEEEEEE    EEEE ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                   E E                   ",
            "                   E E                   ",
            "                   E E                   ",
            "                  EE EE                  ",
            "                  EE EE                  ",
            "                  EE EE                  ",
            "                 EAE EAE                 ",
            "                 EAE EAE                 ",
            "                 EAE EAE                 ",
            "                EEAE EAEE                ",
            "                EEAE EAEE                ",
            "                EEAE EAEE                ",
            "               EEAAE EAAEE               ",
            "               EEAEE EEAEE               ",
            "               EEAEE EEAEE               ",
            "              EEEAEE EEAEEE              ",
            "              EEEAEE EEAEEE              ",
            "              EEEAEE EEAEEE              ",
            "             EEEAAEE EEAAEEE             ",
            "             EEEAEEE EEEAEEE             ",
            "             EEEAEEE EEEAEEE             ",
            "            EEEEAEEE EEEAEEEE            ",
            "            EEEEAEEE EEEAEEEE            ",
            "    E       EEEEAEEE EEEAEEEE       E    ",
            "    E      EEEEEAEEE EEEAEEEEE      E    ",
            "   EE      EEEEEAEEE EEEAEEEEE      EE   ",
            "   EE      EEEAAAEEE EEEAAAEEE      EE   ",
            "  EEE     EEEEAEEEEE EEEEEAEEEE     EEE  ",
            "  EEE     EEAAAEEEEE EEEEEAAAEE     EEE  ",
            " EEEE     EEAEEEEEEE EEEEEEEAEE     EEEE ",
            " EEEE    EEEEEEEEEEEEEEEEEEEEEEE    EEEE ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    E                               E    ",
            "    E                               E    ",
            "   EE                               EE   ",
            "   EE                               EE   ",
            "  EEE          EE       EE          EEE  ",
            "  EEE          EE       EE          EEE  ",
            " EEEE        EEEE       EEEE        EEEE ",
            " EEEE    EEEEEEEEEEEEEEEEEEEEEEE    EEEE ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    E                               E    ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "               EE       EE               ",
            "             EEEE       EEEE             ",
            "  EE     EEEEEEEEEEEEEEEEEEEEEEE     EE  ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    E                               E    ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "               EE       EE               ",
            "  EE      EEEEEEEEEEEEEEEEEEEEE      EE  ",
            "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     E                             E     ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "               EE       EE               ",
            "   EE     EEEEEEEEEEEEEEEEEEEEE     EE   ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     E                             E     ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "   EE      EEEEEEEEEEEEEEEEEEE      EE   ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     E                             E     ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "               EE       EE               ",
            "   EE       EEEEEEEEEEEEEEEEEE      EE   ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "      E                           E      ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    EE      EEEEEEEEEEEEEEEEE      EE    ",
            " DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "      E                           E      ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "    EE       EEEEEEEEEEEEEEE       EE    ",
            "  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "       E                         E       ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     EE        EEEEEEEEEEE        EE     ",
            "  DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD  "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "        E                       E        ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "     EEE         EEEEEEE         EEE     ",
            "   DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD   "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "         E                     E         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "      EEE                       EEE      ",
            "    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD    "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "          E                   E          ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "       EEE                     EEE       ",
            "    DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD    "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "           EE               EE           ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "        EEE                   EEE        ",
            "     DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD     "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "             EEE         EEE             ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "         EEEE               EEEE         ",
            "      DDDDDDDDDDDDDDDDDDDDDDDDDDDDD      "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                EEEEEEEEE                ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "           EEEEE  EEEEE  EEEEE           ",
            "       DDDDDDDDDDDDDDDDDDDDDDDDDDD       "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "             EEEEEEEEEEEEEEE             ",
            "         DDDDDDDDDDDDDDDDDDDDDDD         "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "                EEEEEEEEE                ",
            "          DDDDDDDDDDDDDDDDDDDDD          "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                  EEEEE                  ",
            "                  EEEEE                  ",
            "            DDDDDDDDDDDDDDDDD            "
    }, {
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                                         ",
            "                DDDDDDDDD                "
    } };
}
