package serendustry.machine;

import static gregtech.api.util.RelativeDirection.DOWN;
import static gregtech.api.util.RelativeDirection.FRONT;
import static gregtech.api.util.RelativeDirection.LEFT;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.util.ResourceLocation;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import gregtech.api.capability.IEnergyContainer;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.MultiblockAbility;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.api.pattern.PatternMatchContext;
import gregtech.api.unification.material.Materials;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.texture.Textures;
import gregtech.common.blocks.BlockMetalCasing;
import gregtech.common.blocks.MetaBlocks;

public class MetaTileEntityGiantFractionatingColumn extends RecipeMapMultiblockController {

    public MetaTileEntityGiantFractionatingColumn(ResourceLocation rl) {
        super(rl, SerendustryRecipeMaps.GIANT_FRACTIONATING_COLUMN_RECIPES);
    }

    @Override
    public MetaTileEntityGiantFractionatingColumn createMetaTileEntity(IGregTechTileEntity te) {
        return new MetaTileEntityGiantFractionatingColumn(metaTileEntityId);
    }

    @Override
    public boolean hasMaintenanceMechanics() {
        return false;
    }

    @Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);

        List<IEnergyContainer> energyInput = new ArrayList<>(getAbilities(MultiblockAbility.INPUT_ENERGY));
        List<IEnergyContainer> substationInput = new ArrayList<>(
                getAbilities(MultiblockAbility.SUBSTATION_INPUT_ENERGY));

        if (!energyInput.isEmpty() && !substationInput.isEmpty()) {
            invalidateStructure();
        }

        // todo: give error message to multiblock builder and make JEI not show mixed hatches

        /*
         * List<IEnergyContainer> powerInput = new ArrayList<>(getAbilities(MultiblockAbility.INPUT_ENERGY));
         * powerInput.addAll(getAbilities(MultiblockAbility.SUBSTATION_INPUT_ENERGY));
         * 
         * this.powerInput = new EnergyContainerList(powerInput);
         */  // todo: update ceu so this works and check if this even needed
    }

    @Override
    public @NotNull BlockPattern createStructurePattern() {
        return FactoryBlockPattern.start(LEFT, DOWN, FRONT)
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAACAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    AAAAAAA    ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BAAAAAAAAAB  ")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "    AAAAAAA    ",
                        "   A       A   ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BAAAAAAAAAAAB ")
                .aisle(
                        "               ",
                        "               ",
                        "     AAAAA     ",
                        "   AA     AA   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "      BBB      ",
                        "      AAA      ",
                        "    AA   AA    ",
                        "   A       A   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "     B   B     ",
                        "     AAAAA     ",
                        "    A     A    ",
                        "   A       A   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "     B B B     ",
                        "     AAAAA     ",
                        "    A     A    ",
                        "   A       A   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "     B   B     ",
                        "     AAAAA     ",
                        "    A     A    ",
                        "   A       A   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "      BBB      ",
                        "      AAA      ",
                        "    AA   AA    ",
                        "   A       A   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "               ",
                        "               ",
                        "     AAAAA     ",
                        "   AA     AA   ",
                        "  A         A  ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BA           AB",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        " A           A ",
                        "BAAAAAAAAAAAAAB")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "    AAAAAAA    ",
                        "   A       A   ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BA         AB ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        "  A         A  ",
                        " BAAAAAAAAAAAB ")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    AAAAAAA    ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BA       AB  ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "   A       A   ",
                        "  BAAAAAAAAAB  ")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "    AAAAAAA    ",
                        "   BAAAAAAAB   ")
                .aisle(
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ",
                        "               ",
                        "               ",
                        "               ",
                        "               ",
                        "    BBBBBBB    ")
                .where('C', selfPredicate())
                .where('A',
                        states(MetaBlocks.METAL_CASING.getState(BlockMetalCasing.MetalCasingType.TUNGSTENSTEEL_ROBUST)) // todo
                                .setMinGlobalLimited(1490)
                                .or(autoAbilities(false, false, true, true, true, true, false))
                                .or(abilities(MultiblockAbility.INPUT_ENERGY).setPreviewCount(0).setMinGlobalLimited(0)
                                        .setMaxGlobalLimited(2))
                                .or(abilities(MultiblockAbility.SUBSTATION_INPUT_ENERGY).setPreviewCount(1)
                                        .setMaxGlobalLimited(1)))
                .where('B', frames(Materials.NaquadahAlloy))
                .build();
    }

    public ICubeRenderer getBaseTexture(@Nullable IMultiblockPart part) {
        return Textures.ROBUST_TUNGSTENSTEEL_CASING; // todo
    }
}
