package serendustry.machine;

import gregtech.api.capability.IEnergyContainer;
import gregtech.api.capability.impl.EnergyContainerList;
import gregtech.api.metatileentity.multiblock.MultiblockAbility;
import gregtech.api.pattern.PatternMatchContext;
import gregtech.common.blocks.BlockMetalCasing;
import gregtech.common.blocks.BlockWireCoil;
import net.minecraft.block.state.IBlockState;
import net.minecraft.util.ResourceLocation;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.texture.Textures;
import gregtech.common.blocks.BlockMachineCasing;
import gregtech.common.blocks.MetaBlocks;

import java.util.ArrayList;
import java.util.List;

import static gregtech.api.util.RelativeDirection.*;

public class MetaTileEntityNebulaicNexus extends RecipeMapMultiblockController {

    //private IEnergyContainer powerInput; // todo: update ceu so this works and check if this even needed

    public MetaTileEntityNebulaicNexus(ResourceLocation rl) {
        super(rl, SerendustryRecipeMaps.NEBULAIC_NEXUS_RECIPES);
    }

    @Override
    public MetaTileEntityNebulaicNexus createMetaTileEntity(IGregTechTileEntity te) {
        return new MetaTileEntityNebulaicNexus(metaTileEntityId);
    }

    @Override
    public boolean hasMaintenanceMechanics() {
        return false;
    }

    @Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);

        List<IEnergyContainer> energyInput = new ArrayList<>(getAbilities(MultiblockAbility.INPUT_ENERGY));
        List<IEnergyContainer> substationInput = new ArrayList<>(getAbilities(MultiblockAbility.SUBSTATION_INPUT_ENERGY));

        if(!energyInput.isEmpty() && !substationInput.isEmpty()) { 
            invalidateStructure();
        }

        // todo: give error message to multiblock builder and make JEI not show mixed hatches

        /*List<IEnergyContainer> powerInput = new ArrayList<>(getAbilities(MultiblockAbility.INPUT_ENERGY));
        powerInput.addAll(getAbilities(MultiblockAbility.SUBSTATION_INPUT_ENERGY));

        this.powerInput = new EnergyContainerList(powerInput);*/  // todo: update ceu so this works and check if this even needed
    }

    @Override
    public @NotNull BlockPattern createStructurePattern() {
        return FactoryBlockPattern.start(LEFT, DOWN, FRONT)
                .aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "             CCCCC             ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "             CCCCC             "
                ).aisle(
                        "                               ",
                        "                               ",
                        "              CCC              ",
                        "            CCCCCCC            ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "              BBB              ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "              BBB              ",
                        "            CCBBBCC            "
                ).aisle(
                        "                               ",
                        "               C               ",
                        "             CCBCC             ",
                        "             C B C             ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "              BBB              ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "             BBCBB             "
                ).aisle(
                        "                               ",
                        "              CCC              ",
                        "            CCBBBCC            ",
                        "          C C BBB C C          ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "          C   CCC   C          "
                ).aisle(
                        "               C               ",
                        "             CCCCC             ",
                        "           CCBBBBBCC           ",
                        "         CCC BBBBB CCC         ",
                        "             BBBBB             ",
                        "             BBBBB             ",
                        "             BBBBB             ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               A               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "         CCB CCCCC BCC         "
                ).aisle(
                        "              CCC              ",
                        "            CCCCCCC            ",
                        "          CCBBBBBBBCC          ",
                        "     CCCCCC BBBBBBB CCCCCC     ",
                        "     C      BBBBBBB      C     ",
                        "     C      BBBBBBB      C     ",
                        "    CC      BBBBBBB      CC    ",
                        "    C        BBBBB        C    ",
                        "    C        BBBBB        C    ",
                        "   CC        BBBBB        CC   ",
                        "   C         BBBBB         C   ",
                        "   C          BBB          C   ",
                        " CCC          BBB          CCC ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        " CCC                       CCC ",
                        "   C          AAA          C   ",
                        "   C      BB  AAA  BB      C   ",
                        "   CC    B    AAA    B    CC   ",
                        "    C    B           B    C    ",
                        "    C    B           B    C    ",
                        "    CC   B           B   CC    ",
                        "     C   B     C     B   C     ",
                        "     C   BB   CCC   BB   C     ",
                        "     CCCCCBBCCCCCCCBBCCCCC     "
                ).aisle(
                        "             CCCCC             ",
                        "           CCCCCCCCC           ",
                        "      CCCCCBBBBBBBBBCCCCC      ",
                        "     CCCCCCBBBBBBBBBCCCCCC     ",
                        "    CCCCCC BBBBBBBBB CCCCCC    ",
                        "    CCC    BBBBBBBBB    CCC    ",
                        "    CC     BBBBBBBBB     CC    ",
                        "   CCC      BBBBBBB      CCC   ",
                        "   CCC      BBBBBBB      CCC   ",
                        "   CC       BBBBBBB       CC   ",
                        "  CCC       BBBBBBB       CCC  ",
                        " CCCC        BBBBB        CCCC ",
                        "CCCC         BBBBB         CCCC",
                        " CC          BBBBB          CC ",
                        "              BBB              ",
                        "              BBB              ",
                        " CC            B            CC ",
                        "CCCC           A           CCCC",
                        " CCCC     BB  AAA  BB     CCCC ",
                        "  CCC    BBBBAA AABBBB    CCC  ",
                        "   CC   BBB   AAA   BBB   CC   ",
                        "   CCC  BB     A     BB  CCC   ",
                        "   CCC  BB           BB  CCC   ",
                        "    CC  BB     D     BB  CC    ",
                        "    CCC BB    CCC    BB CCC    ",
                        "    CCC  BB  CCCCC  BB  CCC    ",
                        "     CCCCCBCCCCCCCCCBCCCCC     "
                ).aisle(
                        "              CCC              ",
                        "            CCCCCCC            ",
                        "          CCBBBBBBBCC          ",
                        "     CCCCCC BBBBBBB CCCCCC     ",
                        "     C      BBBBBBB      C     ",
                        "     C      BBBBBBB      C     ",
                        "    CC      BBBBBBB      CC    ",
                        "    C        BBBBB        C    ",
                        "    C        BBBBB        C    ",
                        "   CC        BBBBB        CC   ",
                        "   C         BBBBB         C   ",
                        "   C          BBB          C   ",
                        " CCC          BBB          CCC ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        " CCC                       CCC ",
                        "   C          AAA          C   ",
                        "   C      BB  AAA  BB      C   ",
                        "   CC    B    AAA    B    CC   ",
                        "    C    B           B    C    ",
                        "    C    B           B    C    ",
                        "    CC   B           B   CC    ",
                        "     C   B     C     B   C     ",
                        "     C   BB   CCC   BB   C     ",
                        "     CCCCCBBCCCCCCCBBCCCCC     "
                ).aisle(
                        "               C               ",
                        "             CCCCC             ",
                        "           CCBBBBBCC           ",
                        "         CCC BBBBB CCC         ",
                        "             BBBBB             ",
                        "             BBBBB             ",
                        "             BBBBB             ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               A               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "         CCB CCCCC BCC         "
                ).aisle(
                        "                               ",
                        "              CCC              ",
                        "            CCBBBCC            ",
                        "          C C BBB C C          ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "          C   CCC   C          "
                ).aisle(
                        "                               ",
                        "               C               ",
                        "             CCBCC             ",
                        "             C B C             ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "              BBB              ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "             BBCBB             "
                ).aisle(
                        "                               ",
                        "                               ",
                        "              CCC              ",
                        "            CCCCCCC            ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "              BBB              ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "              BBB              ",
                        "            CCBBBCC            "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "             CCCCC             ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "              BBB              ",
                        "             CCCCC             "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "               B               ",
                        "                               ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "              CCC              ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               "
                ).aisle(
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "               C               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ",
                        "                               ")

                .where('D', selfPredicate())
                .where('C', states(MetaBlocks.METAL_CASING.getState(BlockMetalCasing.MetalCasingType.PTFE_INERT_CASING)) // todo: some sort of superdense carbide casing?
                        .setMinGlobalLimited(803).or(autoAbilities(false, false, true, true, true, true, false))
                        .or(abilities(MultiblockAbility.INPUT_ENERGY).setPreviewCount(0).setMinGlobalLimited(0).setMaxGlobalLimited(2))
                        .or(abilities(MultiblockAbility.SUBSTATION_INPUT_ENERGY).setPreviewCount(1).setMaxGlobalLimited(1)))
                        .where('B', states(MetaBlocks.METAL_CASING.getState(BlockMetalCasing.MetalCasingType.TITANIUM_STABLE))) // todo: adamantium casing
                .where('A', states(MetaBlocks.WIRE_COIL.getState(BlockWireCoil.CoilType.TRITANIUM)))
                .where(' ', any())
                .build();
    }

    public ICubeRenderer getBaseTexture(@Nullable IMultiblockPart part) {
        return Textures.INERT_PTFE_CASING; // todo
    }
}
